name: Mod Build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: Install NuGet client
        uses: warrenbuckley/Setup-Nuget@v1

      - name: Setup tModLoader
        uses: chi-rei-den/ModLoaderTools@v1
        with:
          command: setup

      - name: Build Mod
        uses: chi-rei-den/ModLoaderTools@v1
        with:
          command: build
          path: Localizer

      - name: Restore NuGet Packages
        run: nuget restore Localizer.sln -Verbosity detailed

      - name: MSBuild Squid ModPatch
        run: |
          & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" Localizer.sln /p:Configuration=Release /p:Platform=x86

      - name: Patch Mod
        run: '& "$ENV:GITHUB_WORKSPACE\ModPatch\bin\Release\ModPatch.exe"'

      - name: Publish Mod
        uses: chi-rei-den/ModLoaderTools@v1
        with:
          command: publish
          path: Localizer
        env:
          steamid64: ${{ secrets.steamid64 }}
          passphrase: ${{ secrets.mod_browser_passphrase }}

      - name: Clean artifact
        run: |
          mkdir .\Artifact\Artifact\
          Copy-Item -Path "$ENV:UserProfile\Documents\My Games\Terraria\ModLoader\Mods\*" -Destination .\Artifact\Artifact
          del .\Artifact\Artifact\enabled.json

      - uses: actions/upload-artifact@master
        with:
          name: Build Artifact
          path: Artifact

      - name: Run Tests
        run: '& "$ENV:UserProfile\.nuget\packages\xunit.runner.console\2.4.1\tools\net472\xunit.console.x86.exe" ".\LocalizerTest\bin\Release\LocalizerTest.dll"'